// Generated by CoffeeScript 2.3.1
var correctCapitalization, newline_match, sentence_match, start_match, tempah;

start_match = /^([a-z])/;

sentence_match = /([\.!?]) ([a-z])/g;

newline_match = /\n([a-z])/g;

correctCapitalization = function(str) {
  if (!str.length) {
    return str;
  }
  str[0] = str[0].toUpperCase();
  str = str.replace(start_match, function(matched, letter) {
    return letter.toUpperCase();
  });
  str = str.replace(newline_match, function(matched, letter) {
    return '\n' + letter.toUpperCase();
  });
  str = str.replace(sentence_match, function(matched, punctuation, letter) {
    return punctuation + ' ' + letter.toUpperCase();
  });
  return str;
};

module.exports = tempah = function(template, values, filters = {}, options = {}) {
  var filter, filter_name, i, len, templated, value, variable, variable_name, variables;
  variables = template.match(/\$[a-zA-Z_]+(\|[a-zA-Z]+)?/g);
  if (!(variables != null ? variables.length : void 0)) {
    return template;
  }
  templated = template.slice(0);
  for (i = 0, len = variables.length; i < len; i++) {
    variable = variables[i];
    [variable_name, filter_name] = variable.slice(1).split('|');
    value = values[variable_name];
    if (value == null) {
      throw `No such value ${variable_name}`;
    }
    if (filter_name != null) {
      filter = filters[filter_name];
      if (filter == null) {
        throw `No such filter ${filter_name}`;
      }
      value = filter(value);
    }
    templated = templated.replace(variable, value);
  }
  if (options.correct_capitalization) {
    templated = correctCapitalization(templated);
  }
  return templated;
};
