// Generated by CoffeeScript 1.12.7
var tempah;

module.exports = tempah = function(template, values, filters) {
  var filter, filter_name, i, len, ref, templated, value, variable, variable_name, variables;
  variables = template.match(/\$[a-zA-Z_]+(\|[a-zA-Z]+)?/g);
  if (!(variables != null ? variables.length : void 0)) {
    return template;
  }
  templated = template.slice(0);
  for (i = 0, len = variables.length; i < len; i++) {
    variable = variables[i];
    ref = variable.slice(1).split('|'), variable_name = ref[0], filter_name = ref[1];
    value = values[variable_name];
    if (value == null) {
      throw "No such value " + variable_name;
    }
    if (filter_name != null) {
      filter = filters[filter_name];
      if (filter == null) {
        throw "No such filter " + filter_name;
      }
      value = filter(value);
    }
    templated = templated.replace(variable, value);
  }
  return templated;
};
