// Generated by CoffeeScript 1.12.7
var tempah;

module.exports = tempah = function(template, values, filters) {
  var filter, filter_name, i, len, ref, templated, value, variable, variable_name, variables;
  variables = template.match(/\$[a-zA-Z_]+(\|[a-zA-Z]+)?/g);
  templated = template.slice(0);
  for (i = 0, len = variables.length; i < len; i++) {
    variable = variables[i];
    ref = variable.slice(1).split('|'), variable_name = ref[0], filter_name = ref[1];
    value = values[variable_name];
    if (filter_name != null) {
      filter = filters[filter_name];
      value = filter(value);
    }
    templated = templated.replace(variable, value);
  }
  return templated;
};
